### ISSUE TITLE
why make it open source if you're just going to encrypt the code?

### ISSUE THREAD

**Issue by hellidox** [alexcodito/StickFightTheGameTrainer#2]
and add a license, for god's sake.

**Comment by alexcodito** [comment]
MIT License has now been added (fully permissive and only requiring attribution).

@hellidox I did not initially expect anyone to find any interest in this repo (or even come across it), and it only served as an entry for my portfolio.

It was initially encrypted and obfuscated to prevent tampering by script kiddies who tried to cheat in online lobbies. Interest in the game dwindled in the half-decade since the date when mod was originally released, which is why I made it public. I didn't find time or motivation to remove the anti-tampering mechanisms though.
